@host=http://localhost:8080/service/config

### Get config
GET {{host}}?id=1&field=name,description,type,default http/1.1


### Post config
POST {{host}} http/1.1
Content-Type: application/json

{
    "name": "test_config_5",
    "description": "test_config_5",
    "type": "test_type_5",
    "value": "test_value_5",
    "default": "test_default_5",
    "required": true,
    "readonly": true,
    "hidden": true,
    "options": [
      {
        "name": "test_option_5",
        "value": "test_value_5"
      }
    ]
}

### Patch config
PATCH {{host}} http/1.1
Content-Type: application/json

{
    "configId": 1,
    "name": "test_config_4",
    "description": "test_config_4",
    "value": "test_value_4"
}